/*
  # Seed Round 2 Questions - 100 Advanced Questions

  ## Round 2 Questions
  Advanced level questions for students who qualified from Round 1
  No questions overlap with Round 1

  ## Question Types
  - Advanced Mathematics
  - Advanced Science
  - Technology & Computing
  - Advanced Literature & History
*/

-- Insert Round 2 Questions (100 questions - Advanced)
INSERT INTO round2_questions (question_text, option_a, option_b, option_c, correct_answer, question_order, question_type) VALUES
('What is the derivative of x²?', 'x', '2x', 'x³', 'B', 1, 'Mathematics'),
('Who proposed the atomic theory?', 'John Dalton', 'Niels Bohr', 'Ernest Rutherford', 'A', 2, 'Science'),
('What is the capital of Kazakhstan?', 'Almaty', 'Astana', 'Bishkek', 'B', 3, 'Geography'),
('If log₂(x) = 5, what is x?', '16', '32', '64', 'B', 4, 'Mathematics'),
('What is the pH of pure water?', '6', '7', '8', 'B', 5, 'Science'),
('Which programming language was created first?', 'C', 'FORTRAN', 'BASIC', 'B', 6, 'Technology'),
('What is the integral of 1/x?', 'x²', 'ln|x|', '1/x²', 'B', 7, 'Mathematics'),
('Who wrote 1984?', 'Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'B', 8, 'Literature'),
('What is Avogadros number?', '6.02 × 10²³', '6.02 × 10²²', '6.02 × 10²⁴', 'A', 9, 'Science'),
('Solve: 2x² - 8 = 0', 'x = ±2', 'x = ±3', 'x = ±4', 'A', 10, 'Mathematics'),
('Which element has atomic number 79?', 'Silver', 'Gold', 'Platinum', 'B', 11, 'Science'),
('What is sin(30°)?', '0.5', '0.866', '1', 'A', 12, 'Mathematics'),
('Who formulated the three laws of motion?', 'Galileo', 'Isaac Newton', 'Albert Einstein', 'B', 13, 'Science'),
('What is the square root of 256?', '14', '16', '18', 'B', 14, 'Mathematics'),
('Which country hosted the first Olympic Games?', 'Italy', 'Greece', 'France', 'B', 15, 'History'),
('If a² + b² = c² and a=3, b=4, what is c?', '5', '6', '7', 'A', 16, 'Mathematics'),
('What is the chemical formula for sulfuric acid?', 'H₂SO₃', 'H₂SO₄', 'H₃SO₄', 'B', 17, 'Science'),
('Who painted The Starry Night?', 'Claude Monet', 'Vincent van Gogh', 'Pablo Picasso', 'B', 18, 'Art'),
('What is 15!/(14!)?', '14', '15', '16', 'B', 19, 'Mathematics'),
('Which organ produces insulin?', 'Liver', 'Pancreas', 'Kidney', 'B', 20, 'Science'),
('What is cos(60°)?', '0.5', '0.866', '1', 'A', 21, 'Mathematics'),
('Who discovered radioactivity?', 'Marie Curie', 'Henri Becquerel', 'Pierre Curie', 'B', 22, 'Science'),
('What is the sum of first 10 natural numbers?', '45', '50', '55', 'C', 23, 'Mathematics'),
('Which gas law relates pressure and volume?', 'Charles Law', 'Boyle Law', 'Ideal Gas Law', 'B', 24, 'Science'),
('If f(x) = 3x + 2, what is f(5)?', '15', '17', '19', 'B', 25, 'Mathematics'),
('What is the speed of sound in air?', '243 m/s', '343 m/s', '443 m/s', 'B', 26, 'Science'),
('What is tan(45°)?', '0.5', '1', '1.732', 'B', 27, 'Mathematics'),
('Who developed the periodic table?', 'Dmitri Mendeleev', 'Marie Curie', 'Ernest Rutherford', 'A', 28, 'Science'),
('What is 2⁸?', '128', '256', '512', 'B', 29, 'Mathematics'),
('Which planet has the Great Red Spot?', 'Mars', 'Jupiter', 'Saturn', 'B', 30, 'Science'),
('Solve: x² - 5x + 6 = 0', 'x = 2, 3', 'x = 1, 6', 'x = -2, -3', 'A', 31, 'Mathematics'),
('What is the molecular formula of glucose?', 'C₆H₁₂O₆', 'C₅H₁₀O₅', 'C₇H₁₄O₇', 'A', 32, 'Science'),
('What is log₁₀(100)?', '1', '2', '3', 'B', 33, 'Mathematics'),
('Who invented calculus?', 'Euler', 'Newton & Leibniz', 'Gauss', 'B', 34, 'History'),
('What is the area of circle with radius 7?', '44π', '49π', '98π', 'B', 35, 'Mathematics'),
('What is the electron configuration of Carbon?', '1s² 2s² 2p²', '1s² 2s² 2p³', '1s² 2s² 2p⁴', 'A', 36, 'Science'),
('If 2ˣ = 128, what is x?', '6', '7', '8', 'B', 37, 'Mathematics'),
('Which scientist proposed evolution theory?', 'Mendel', 'Darwin', 'Lamarck', 'B', 38, 'Science'),
('What is the integral of 2x dx?', 'x', 'x²', '2x²', 'B', 39, 'Mathematics'),
('What is the hardest natural substance?', 'Gold', 'Diamond', 'Platinum', 'B', 40, 'Science'),
('What is the value of π to 2 decimal places?', '3.12', '3.14', '3.16', 'B', 41, 'Mathematics'),
('Who discovered DNA structure?', 'Watson & Crick', 'Mendel', 'Darwin', 'A', 42, 'Science'),
('What is 5³ - 3³?', '88', '98', '108', 'B', 43, 'Mathematics'),
('What is the noble gas in period 2?', 'Helium', 'Neon', 'Argon', 'B', 44, 'Science'),
('Solve: 3x + 7 = 28', 'x = 6', 'x = 7', 'x = 8', 'B', 45, 'Mathematics'),
('Which force holds atoms together?', 'Gravitational', 'Nuclear', 'Electromagnetic', 'C', 46, 'Science'),
('What is the slope of y = 3x + 5?', '2', '3', '5', 'B', 47, 'Mathematics'),
('What is the SI unit of electric current?', 'Volt', 'Ampere', 'Watt', 'B', 48, 'Science'),
('If matrix A is 2×3 and B is 3×4, what is AB dimensions?', '2×3', '2×4', '3×4', 'B', 49, 'Mathematics'),
('What is the acceleration due to gravity?', '8.8 m/s²', '9.8 m/s²', '10.8 m/s²', 'B', 50, 'Science'),
('What is the sum of angles in pentagon?', '360°', '450°', '540°', 'C', 51, 'Mathematics'),
('Which law explains action-reaction?', 'First Law', 'Second Law', 'Third Law', 'C', 52, 'Science'),
('What is the cube root of 27?', '2', '3', '4', 'B', 53, 'Mathematics'),
('What is the charge of an electron?', '-1.6 × 10⁻¹⁹C', '+1.6 × 10⁻¹⁹C', '0', 'A', 54, 'Science'),
('If sin(x) = 0.5, what is x in 0-90°?', '30°', '45°', '60°', 'A', 55, 'Mathematics'),
('What is the formula for kinetic energy?', '½mv', '½mv²', 'mv²', 'B', 56, 'Science'),
('What is 15% of 240?', '32', '36', '40', 'B', 57, 'Mathematics'),
('Which particle has no charge?', 'Proton', 'Electron', 'Neutron', 'C', 58, 'Science'),
('Solve: |x - 3| = 5', 'x = 2, 8', 'x = -2, 8', 'x = 2, -8', 'B', 59, 'Mathematics'),
('What is Ohms Law?', 'V = IR', 'V = I/R', 'V = I + R', 'A', 60, 'Science'),
('What is the nth term of arithmetic sequence?', 'a + nd', 'a + (n-1)d', 'a + (n+1)d', 'B', 61, 'Mathematics'),
('What is the symbol for electrical resistance?', 'R', 'Z', 'Ω', 'C', 62, 'Science'),
('If log(x) + log(y) = log(20), what is xy?', '10', '20', '40', 'B', 63, 'Mathematics'),
('What is the molar mass of water?', '16g/mol', '18g/mol', '20g/mol', 'B', 64, 'Science'),
('What is determinant of matrix [[2,3],[4,5]]?', '-2', '-1', '2', 'A', 65, 'Mathematics'),
('What is the formula for photosynthesis?', '6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂', 'CO₂ + H₂O → CH₄ + O₂', 'C₆H₁₂O₆ → 6CO₂ + 6H₂O', 'A', 66, 'Science'),
('What is (a + b)²?', 'a² + b²', 'a² + 2ab + b²', 'a² - 2ab + b²', 'B', 67, 'Mathematics'),
('What is Newton universal gravitation constant?', '6.67 × 10⁻¹¹', '6.67 × 10⁻¹⁰', '6.67 × 10⁻¹²', 'A', 68, 'Science'),
('What is sum of infinite GP: 1 + 1/2 + 1/4 + ...?', '1', '2', '3', 'B', 69, 'Mathematics'),
('What is the SI unit of force?', 'Joule', 'Newton', 'Pascal', 'B', 70, 'Science'),
('If f(x) = x² - 4x + 3, what is f(2)?', '-1', '0', '1', 'A', 71, 'Mathematics'),
('What is wavelength range of visible light?', '200-400nm', '400-700nm', '700-1000nm', 'B', 72, 'Science'),
('What is probability of heads twice in 2 tosses?', '0.25', '0.5', '0.75', 'A', 73, 'Mathematics'),
('What is the formula for momentum?', 'mv', 'mv²', '½mv²', 'A', 74, 'Science'),
('What is binomial expansion of (x + y)²?', 'x² + y²', 'x² + 2xy + y²', 'x² + xy + y²', 'B', 75, 'Mathematics'),
('What is melting point of ice in Kelvin?', '273K', '373K', '100K', 'A', 76, 'Science'),
('Solve quadratic: x² - 7x + 12 = 0', 'x = 2, 5', 'x = 3, 4', 'x = 1, 12', 'B', 77, 'Mathematics'),
('What is frequency of AC current in Sri Lanka?', '50 Hz', '60 Hz', '100 Hz', 'A', 78, 'Science'),
('What is differentiation of sin(x)?', 'cos(x)', '-cos(x)', 'sin(x)', 'A', 79, 'Mathematics'),
('What is the symbol for Gold?', 'Go', 'Au', 'Gd', 'B', 80, 'Science'),
('If vectors a=(2,3) and b=(1,4), what is a+b?', '(3,5)', '(3,7)', '(2,7)', 'B', 81, 'Mathematics'),
('What is the formula for Ideal Gas Law?', 'PV = nRT', 'PV = RT', 'P = nRT', 'A', 82, 'Science'),
('What is area of trapezium with h=5, a=3, b=7?', '20', '25', '30', 'B', 83, 'Mathematics'),
('What is oxidation state of O in H₂O?', '-1', '-2', '0', 'B', 84, 'Science'),
('What is lim(x→0) sin(x)/x?', '0', '1', '∞', 'B', 85, 'Mathematics'),
('What is unit of magnetic flux?', 'Tesla', 'Weber', 'Henry', 'B', 86, 'Science'),
('What is inverse of y = 2x + 3?', 'y = (x-3)/2', 'y = (x+3)/2', 'y = 2x-3', 'A', 87, 'Mathematics'),
('What is human body temperature in Kelvin?', '300K', '310K', '320K', 'B', 88, 'Science'),
('What is common ratio of GP: 2, 6, 18, ...?', '2', '3', '4', 'B', 89, 'Mathematics'),
('What is the lens formula?', '1/f = 1/v + 1/u', '1/f = 1/v - 1/u', 'f = uv', 'B', 90, 'Mathematics'),
('If sec²(θ) = 1 + tan²(θ), what is sec(0°)?', '0', '1', '∞', 'B', 91, 'Mathematics'),
('What is specific heat capacity of water?', '4.18 J/g°C', '2.09 J/g°C', '6.28 J/g°C', 'A', 92, 'Science'),
('What is equation of circle (x-h)² + (y-k)² =?', 'r', 'r²', '2r', 'B', 93, 'Mathematics'),
('What is bond angle in water molecule?', '104.5°', '109.5°', '120°', 'A', 94, 'Science'),
('What is value of e to 2 decimal places?', '2.65', '2.72', '2.82', 'B', 95, 'Mathematics'),
('What is unit of electric charge?', 'Ampere', 'Coulomb', 'Volt', 'B', 96, 'Science'),
('What is distance formula in 3D?', '√(x² + y² + z²)', '√(x² + y²)', 'x² + y² + z²', 'A', 97, 'Mathematics'),
('What is half-life of Carbon-14?', '5,730 years', '10,000 years', '1,000 years', 'A', 98, 'Science'),
('If matrix [[a,b],[c,d]], determinant is?', 'ad - bc', 'ac - bd', 'ab - cd', 'A', 99, 'Mathematics'),
('What is quantum number for spin?', '±½', '±1', '0', 'A', 100, 'Science');
